### ISSUE TITLE
Nested keys being lost

### ISSUE THREAD

**Issue by jackdclark** [vigour-io/unflatten#1]
Hello! I just ran into a bug with `unflatten`. If a key is passed in at the same time as a nested path that has the same top-level key, the nested path gets lost in the result, e.g:

```
> const unflatten = require('unflatten')
undefined
> unflatten({ 'a.b': 'c', a: 'b' })
{ a: 'b' }
```

**Comment by miketheprogrammer** [comment]
This is not a bug, it is bad data. You are telling it to overwrite the previous value of `a` with `'b'`
Closing.

**Comment by miketheprogrammer** [comment]
Hmm, guess I am only an npm contributor now.

**Comment by jackdclark** [comment]
You're completely right. This was a long time ago so I may have oversimplified my example for the issue that I was running into, but I can't remember exactly. Until then, let's close this @miketheprogrammer. Thank you.
